name: firstone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  introduction_screen: ^3.1.12
  lottie: ^2.7.0
  flutter_local_notifications: ^16.2.0
  permission_handler: ^11.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.5
  url_launcher: ^6.0.3
  http: ^1.1.2
  intl: ^0.17.0
  flutter_sound: ^9.2.13
  firebase_storage: ^11.5.5
  image_picker: ^1.0.4
  provider: ^6.1.1
  fl_chart: ^0.65.0
  charts_flutter: ^0.12.0
  flutter_image_compress: ^2.1.0
  fluttertoast: ^8.2.4
  image: ^4.1.3
  path_provider: ^2.1.1
  cached_network_image: ^3.3.0
  awesome_notifications: any
  firebase_messaging: ^14.7.10
  timezone: ^0.9.2
  mockito: ^5.4.4
  url_launcher_platform_interface: ^2.3.1
  

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/Animation - 1699395967791.json
    - assets/img/
